baseURL: "https://pmoscode.github.io/pmoscode-website"
languageCode: "en-us"
title: "pmoscode"
copyright: pmoscode
theme: github.com/CaiJimmy/hugo-theme-stack/v3

module:
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3

languages:
  en:
    languageName: English
    title: pmoscode
    weight: 1
    params:
      description: We can
      sidebar:
        subtitle: Every solution requires a problem...

#  de:
#    languageName: Deutsch
#    title: pmoscode
#    weight: 1
#    params:
#      description: Wir können
#      sidebar:
#        subtitle: Jede Lösung benötigt ein Problem

params:
  pagination:
    pagerSize: 5

  favicon: /favicon.ico

  footer:
    since: 2019

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006

  sidebar:
    avatar:
      enabled: true
      local: true
      src: img/avatar.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-ND 4.0

  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: pmoscode/pmoscode-website
      repoID: R_kgDOKOWT7g
      category: Comment
      categoryID: DIC_kwDOKOWT7s4CcKcj
      mapping: title
      lightTheme: false
      darkTheme: true
      reactionsEnabled: 1
      emitMetadata: 0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 50
    page:
      - type: toc

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/pmoscode
      params:
        icon: brand-github
    - identifier: medium
      name: Medium
      url: https://medium.com/@info_26971
      params:
        icon: brand-medium
    - identifier: substack
      name: Substack
      url: https://pmoscode.substack.com/
      params:
        icon: brand-substack
    - identifier: tumblr
      name: Tumblr
      url: https://www.tumblr.com/blog/pmoscode
      params:
        icon: brand-tumblr
    - identifier: bluesky
      name: Bluesky
      url: https://bsky.app/profile/pmoscode.bsky.social
      params:
        icon: brand-bluesky

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4