version: 3

tasks:
  theme:init:
    desc: Downloads the theme as Hugo module
    cmd: hugo mod vendor

  theme:update:
    desc: Update golang and the theme according to go.mod
    cmd: hugo mod get -u

  serve:
    desc: Starts the dev server
    cmds:
      - rm -Rf public
      - hugo server -D --environment development --logLevel info --disableFastRender

  build:
    desc: Builds the static website
    cmds:
      - rm -Rf public
      - hugo --gc --minify --environment production --logLevel info